### ISSUE TITLE
pxt.cpp 

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt-microbit-core#1]
Shouldn't much of this code (generic runtime for collections, etc) be in pxt?

**Comment by mmoskal** [comment]
The C++ code can currently only sit in the target (pxt-microbit). The idea with this repository, is that it forms a yotta module, which can be referenced by other yotta modules if needed. Though maybe with mbed going away from yotta this is worth some thought...

**Comment by tballmsft** [comment]
Got it.

Sent from my Windows Phone
